name: CI/CD
on:
  push:
    paths:
      - 'terraform/**'
      - 'ansible/**'
  workflow_dispatch:
jobs:
  validate_and_lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: terraform -chdir=terraform init
      - run: terraform -chdir=terraform fmt -check
      - run: terraform -chdir=terraform validate
      - run: yamllint ansible/
  deploy:
    runs-on: self-hosted
    needs: validate_and_lint
    steps:
      - uses: actions/checkout@v3
      - run: terraform -chdir=terraform init
      - run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var "esxi_app_user=${{ secrets.ESXI_APP_USER }}" \
            -var "esxi_app_password=${{ secrets.ESXI_APP_PASSWORD }}" \
            -var "azure_app_subscription_id=${{ secrets.AZURE_APP_SUBSCRIPTION_ID }}"
      - run: ansible-playbook -i ansible/inventory.ini ansible/playbooks/deploy.yml
